/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "bb.h"

CLIENT *setup_rpc(char *host);

void post(char *user, char *article, CLIENT *clnt);
void read(CLIENT *clnt);
void reply(int i, char *user, char *article, CLIENT *clnt);
void choose(int i, CLIENT *clnt);

int main (int argc, char *argv[])
{
    CLIENT *clnt;
	char *host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }

    host = argv[1];
    clnt = setup_rpc(host);

    char user[] = "Eric";

    char testarticle1[] = "Test1";
    char testarticle2[] = "Test2";
    char testarticle3[] = "Test3";
    char testarticle4[] = "Test4";
    char testarticle5[] = "Test5";
    char testarticle6[] = "Test6";

    printf("POSTING ARTICLES\n");
    post(user, testarticle1, clnt);
    post(user, testarticle2, clnt);
    post(user, testarticle3, clnt);
    post(user, testarticle4, clnt);
    reply(4, user, testarticle5, clnt);
    reply(2, user, testarticle6, clnt);

    printf("GETTING LIST\n");
    read(clnt);

    printf("GETTING AN ARTICLE\n");
    choose(4, clnt);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

    exit (0);
}

void post(char *user, char *article, CLIENT *clnt)
{
	bool_t  *result_1;

	result_1 = post_1(user, article, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

}

void read(CLIENT *clnt)
{
    char * *result;

	result = read_1(clnt);
	if (result == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

    printf("%s\n", *result);
}

void reply(int i, char *user, char *article, CLIENT *clnt)
{
    bool_t *result;
	result = reply_1(i, user, article, clnt);
	if (result == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
}

void choose(int i, CLIENT *clnt)
{
    char * *result;

	result = choose_1(i, clnt);
	if (result == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

    printf("%s\n", *result);

}

CLIENT *setup_rpc(char *host)
{
    CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, BULLETIN_PROG, BULLETIN_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    return clnt;

}
