/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <string.h>
#include "backend.h"
#include "bb.h"

bool_t *
post_1_svc(char *user, char *article,  struct svc_req *rqstp)
{
	static bool_t  result;

    result = post_article(user, article);

    if(result)
    {
        printf("New article by %s: %s\n", user, article);
    }
    else
    {
        printf("Failed to publish article\n");
    }

	return &result;
}

char **
read_1_svc(struct svc_req *rqstp)
{
	static char * result;

    result = get_list();

	return &result;
}

char **
choose_1_svc(int id,  struct svc_req *rqstp)
{
	static char * result;

    result = get_article(id);

	return &result;
}

bool_t *
reply_1_svc(int id, char *user, char *article,  struct svc_req *rqstp)
{
	static bool_t  result;

    result = post_reply(id, user, article);

    if(result)
    {
        printf("New article by %s: %s\n" ,user, article);
    }
    else
    {
        printf("Failed to publish article\n");
    }

	return &result;
}
